version: "3"
services:
  cookiemonster:
    image: myr3p0/cookiemonster
    command: -cookie ${COOKIE}
  sublist3r:
    image: myr3p0/sublist3r
    command: -t 50 -d ${TARGET} -o /tmp/sublist3r-output.txt
    volumes:
      - ./:/tmp/
  dnscan:
    image: myr3p0/dnscan
    command: -t 100 -L /dnscan/resolvers.txt -d ${TARGET}
    volumes:
      - ./:/tmp/
  assetfinder:
    image: myr3p0/assetfinder
    command: ${TARGET}
    volumes:
      - ./:/tmp/
  bingip2host:
    image: myr3p0/bing-ip2host
    command: -q -o /tmp/bing-output.txt ${TARGET}
    volumes:
      - ./:/tmp/
  whatweb:
    image: myr3p0/whatweb
    command: -i /tmp/bing-output.txt -a 1 --no-errors
    volumes:
      - ./:/tmp/
  nmap:
    image: myr3p0/nmap
    command: -sV --script http-security-headers,vulners,smb-enum-shares,smb-enum-users,smtp-enum-users,whois-domain,mysql-info,mysql-enum,http-vhosts ${TARGET}
  shuffledns:
    image: myr3p0/shuffledns
    command: -r /resolvers.txt -w /all.txt --silent -o /tmp/shuffledns-output.txt -d ${TARGET}
    volumes:
      - ./:/tmp/
  subfinder:
    image: myr3p0/subfinder
    command: -config /tmp/config.yaml -all -d ${TARGET} -silent -o /tmp/subfinder-output.txt
    volumes:
      - ./:/tmp/
  amass:
    image: myr3p0/amass
    command: enum -passive -r 8.8.8.8 -d ${TARGET} -o /tmp/amass-output.txt
    volumes:
      - ./:/tmp/
  puredns:
    image: myr3p0/puredns
    command: bruteforce /all.txt --resolvers /resolvers.txt ${TARGET} -q -w /tmp/puredns-output.txt
    volumes:
      - ./:/tmp/
  findomain:
    image: myr3p0/findomain
    command: -q -t ${TARGET} --unique-output /tmp/findomain-output.txt
    volumes:
      - ./:/tmp/
  delator:
    image: myr3p0/delator
    command: -d ${TARGET} -s crt
    volumes:
      - ./:/tmp/
  dnstake:
    image: myr3p0/dnstake
    command: -t /tmp/subdomain-output.txt -c 100 -s
    volumes:
      - ./:/tmp/
  puredns-resolve:
    image: myr3p0/puredns
    command: resolve /tmp/subdomain-output.txt --skip-sanitize -q -w /tmp/resolved-subdomain-output.txt -r /tmp/resolvers.txt
    volumes:
      - ./:/tmp/
  httpx:
    image: myr3p0/httpx
    command: -l /tmp/resolved-subdomain-output.txt -o /tmp/httpx-output.txt --silent
    volumes:
      - ./:/tmp/
  httpx-details:
    image: myr3p0/httpx
    command: -l /tmp/httpx-output.txt -status-code -title -tech-detect -ports 8080,10000,20000,2222,7080,9009,7443,2087,2096,8443,4100,2082,2083,2086,9999,2052,9001,9002,7000,7001,8082,8084,8085,8010,9000,2078,2080,2079,2053,2095,4000,5280,8888,9443,5800,631,8000,8008,8087,84,85,86,88,10125,9003,7071,8383,7547,3434,10443,8089,3004,81,4567,7081,82,444,1935,3000,9998,4433,4431,4443,83,90,8001,8099,80,300,443,591,593,832,981,1010,1311,2480,3128,3333,4243,4711,4712,4993,5000,5104,5108,6543,7396,7474,8014,8042,8069,8081,8088,8090,8091,8118,8123,8172,8222,8243,8280,8281,8333,8500,8834,8880,8983,9043,9060,9080,9090,9091,9200,9800,9981,12443,16080,18091,18092,20720,28017 -http2 -random-agent -follow-redirects -silent
    volumes:
      - ./:/tmp/
  cent:
    image: myr3p0/cent
    command: -k -p /tmp/nuclei-templates -t 100
    volumes:
      - ./:/tmp/
  nuclei:
    image: myr3p0/nuclei
    volumes:
      - ./:/tmp/
  nuclei-info:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -duc -nts -t /tmp/nuclei-templates/ -severity info -o /tmp/nuclei[info]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-low:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -duc -nts -t /tmp/nuclei-templates/ -severity low -o /tmp/nuclei[low]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-medium:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -duc -nts -t /tmp/nuclei-templates/ -severity medium -o /tmp/nuclei[medium]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-high:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -duc -nts -t /tmp/nuclei-templates/ -severity high -o /tmp/nuclei[high]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-critical:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -duc -nts -t /tmp/nuclei-templates/ -severity critical -o /tmp/nuclei[critical]-output.txt
    volumes:
      - ./:/tmp/
