version: "3"
services:
  shuffledns:
    image: myr3p0/shuffledns
    command: -r /resolvers.txt -w /all.txt --silent -o /tmp/shuffledns-output.txt -d ${TARGET}
    volumes:
      - ./:/tmp/
  subfinder:
    image: myr3p0/subfinder
    command: -config /tmp/config.yaml -all -d ${TARGET} -silent -o /tmp/subfinder-output.txt
    volumes:
      - ./:/tmp/
  amass:
    image: myr3p0/amass
    command: enum -passive -d ${TARGET} -o /tmp/amass-output.txt
    volumes:
      - ./:/tmp/
  shuffledns-resolve:
    image: myr3p0/shuffledns
    command: -r /resolvers.txt -list /tmp/subdomain-output.txt -silent -o /tmp/resolved-subdomain-output.txt
    volumes:
      - ./:/tmp/
  httpx:
    image: myr3p0/httpx
    command: -l /tmp/resolved-subdomain-output.txt -o /tmp/httpx-output.txt --silent
    volumes:
      - ./:/tmp/
  nuclei:
    image: myr3p0/nuclei
    volumes:
      - ./:/tmp/
  nuclei-info:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -t nuclei-templates/ -severity info -o /tmp/nuclei[info]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-low:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -t nuclei-templates/ -severity low -o /tmp/nuclei[low]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-medium:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -t nuclei-templates/ -severity medium -o /tmp/nuclei[medium]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-high:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -t nuclei-templates/ -severity high -o /tmp/nuclei[high]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-critical:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -t nuclei-templates/ -severity critical -o /tmp/nuclei[critical]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-cve:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -t nuclei-templates/ -tags cve -o /tmp/nuclei[cve]-output.txt
    volumes:
      - ./:/tmp/
