version: "3"
services:
  bingip2host:
    image: myr3p0/bing-ip2host
    command: -q -o /tmp/bing-output.txt ${TARGET}
    volumes:
      - ./:/tmp/
  whatweb:
    image: myr3p0/whatweb
    command: -i /tmp/bing-output.txt -a 1 --no-errors
    volumes:
      - ./:/tmp/
  nmap:
    image: myr3p0/nmap
    command: -sV --script http-security-headers,vulners,smb-enum-shares,smb-enum-users,smtp-enum-users,whois-domain,mysql-info,mysql-enum,http-vhosts ${TARGET}
  shuffledns:
    image: myr3p0/shuffledns
    command: -r /resolvers.txt -w /all.txt --silent -o /tmp/shuffledns-output.txt -d ${TARGET}
    volumes:
      - ./:/tmp/
  subfinder:
    image: myr3p0/subfinder
    command: -config /tmp/config.yaml -all -d ${TARGET} -silent -o /tmp/subfinder-output.txt
    volumes:
      - ./:/tmp/
  amass:
    image: myr3p0/amass
    command: enum -passive -r 8.8.8.8 -d ${TARGET} -o /tmp/amass-output.txt
    volumes:
      - ./:/tmp/
  puredns:
    image: myr3p0/puredns
    command: bruteforce /all.txt --resolvers /resolvers.txt ${TARGET} -q -w /tmp/puredns-output.txt
    volumes:
      - ./:/tmp/
  findomain:
    image: myr3p0/findomain
    command: -q -t ${TARGET} --unique-output /tmp/findomain-output.txt
    volumes:
      - ./:/tmp/
  delator:
    image: myr3p0/delator
    command: -d ${TARGET} -s crt
    volumes:
      - ./:/tmp/
  dnstake:
    image: myr3p0/dnstake
    command: -t /tmp/subdomain-output.txt -c 100 -s
    volumes:
      - ./:/tmp/
  shuffledns-resolve:
    image: myr3p0/shuffledns
    command: -r /resolvers.txt -list /tmp/subdomain-output.txt -silent -o /tmp/resolved-subdomain-output.txt
    volumes:
      - ./:/tmp/
  httpx:
    image: myr3p0/httpx
    command: -l /tmp/resolved-subdomain-output.txt -o /tmp/httpx-output.txt --silent
    volumes:
      - ./:/tmp/
  httpx-details:
    image: myr3p0/httpx
    command: -l /tmp/httpx-output.txt -status-code -title -tech-detect -ports 22,80,443,8443,8080 -http2 -random-agent -follow-redirects -silent
    volumes:
      - ./:/tmp/
  nuclei:
    image: myr3p0/nuclei
    volumes:
      - ./:/tmp/
  nuclei-info:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -nut -t nuclei-templates/ -severity info -o /tmp/nuclei[info]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-low:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -nut -t nuclei-templates/ -severity low -o /tmp/nuclei[low]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-medium:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -nut -t nuclei-templates/ -severity medium -o /tmp/nuclei[medium]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-high:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -nut -t nuclei-templates/ -severity high -o /tmp/nuclei[high]-output.txt
    volumes:
      - ./:/tmp/
  nuclei-critical:
    image: myr3p0/nuclei
    command: -l /tmp/httpx-output.txt -silent -no-interactsh -rl 1000 -bs 200 -c 100 -nut -t nuclei-templates/ -severity critical -o /tmp/nuclei[critical]-output.txt
    volumes:
      - ./:/tmp/
