version: "3"
services:
  shuffledns:
    image: myr3p0/shuffledns
    volumes:
      - ./:/tmp/
  subfinder:
    image: myr3p0/subfinder
    volumes:
      - ./:/tmp/
  amass:
    image: myr3p0/amass
    volumes:
      - ./:/tmp/
  puredns:
    image: myr3p0/puredns
    volumes:
      - ./:/tmp/
  shuffledns-resolve:
    image: myr3p0/shuffledns
    volumes:
      - ./:/tmp/
  httpx:
    image: myr3p0/httpx
    volumes:
      - ./:/tmp/
  nuclei:
    image: myr3p0/nuclei
    volumes:
      - ./:/tmp/
